# Generated by Django 5.0.7 on 2025-02-18 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Survey_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(max_length=254)),
                ('Submitted_Time', models.DateTimeField(auto_now_add=True)),
                ('tea_expense', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('coffee_expense', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('biscuit_expense', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('smoking_expense', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
            ],
        ),
    ]
