# Generated by Django 5.0.7 on 2025-02-23 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Survey_app', '0002_response'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Response',
        ),
        migrations.AddField(
            model_name='form',
            name='Password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='form',
            name='approve',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='form',
            name='biscuit_expense',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='form',
            name='coffee_expense',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='form',
            name='smoking_expense',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='form',
            name='tea_expense',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
