# Generated by Django 5.0.7 on 2025-02-25 09:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Survey_app', '0004_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='unique_id',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True, unique=True),
        ),
    ]
