# Generated by Django 5.0.7 on 2025-02-25 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Survey_app', '0005_form_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='Email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='form',
            name='Link',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
