# Generated by Django 5.0.7 on 2025-02-27 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Survey_app', '0006_alter_form_email_alter_form_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='form',
            old_name='approve',
            new_name='isapprove',
        ),
    ]
